export interface PropertyDTO {
  id: string;
  title: string;
  description: string | null;
  province: string | null;
  town: string | null;
  suburb: string | null;
  address: string | null;
  street_address: string | null;
  postal_code: string | null;
  auction_date: string | null;
  auction_time: string | null;
  auction_venue: string | null;
  auction_price: number | null;
  estimated_value: number | null;
  reserve_price: number | null;
  bedrooms: number | null;
  bathrooms: number | null;
  garages: number | null;
  property_type: string | null;
  status: string | null;
  listing_status: string | null;
  source: string | null;
  source_name: string | null;
  source_url: string | null;
  auction_agency: string | null;
  agency_contact: string | null;
  agency_website: string | null;
  external_listing_id: string | null;
  imported_at: string | null;
  last_verified_at: string | null;
  data_classification: string | null;
  data_quality_score: number | null;
  verification_state: string | null;
  verification_label: string;
  address_display_mode: string | null;
  provenance_notes: string | null;
  latitude: number | null;
  longitude: number | null;
  image: string | null;
  thumbnail: string | null;
  heroImage: string | null;
  blur_placeholder: string | null;
  qualityScore: number | null;
  featured: boolean;
  isSeedOrDemo: boolean;
  isPendingVerification: boolean;
}
