export type PropertyMaster = {
  id: string;
  fingerprint: string;
  fingerprint_version: number;
  identity_confidence: number;
  identity_match_class: string;
  lifecycle_state: string;
  property_status: string;
  property_version: number;
  is_master: boolean;
  title: string | null;
  street_address: string | null;
  suburb: string | null;
  town: string | null;
  province: string | null;
  municipality: string | null;
  ward: string | null;
  postal_code: string | null;
  region: string | null;
  farm_name: string | null;
  farm_number: string | null;
  erf_number: string | null;
  portion_number: string | null;
  latitude: number | null;
  longitude: number | null;
  land_size_sqm: number | null;
  combined_extent: string | null;
  property_type: string | null;
  classification_confidence: number | null;
  primary_image_url: string | null;
  primary_image_hash: string | null;
  verification_state: string | null;
  data_classification: string | null;
  overall_data_quality: number | null;
  first_seen_at: string;
  last_seen_at: string;
  created_at: string;
  updated_at: string;
};

export type AuctionEventRow = {
  id: string;
  property_master_id: string;
  listing_property_id: string | null;
  external_listing_id: string | null;
  agency: string | null;
  auction_date: string | null;
  auction_time: string | null;
  venue: string | null;
  auction_type: string | null;
  reserve_price: number | null;
  opening_bid: number | null;
  winning_bid: number | null;
  guide_price: number | null;
  status: string;
  source_name: string | null;
  source_url: string | null;
  connector_id: string | null;
  verification_state: string | null;
  brochure_link: string | null;
  terms_link: string | null;
  catalogue_link: string | null;
  documents: Record<string, unknown> | null;
  imported_at: string;
  verified_at: string | null;
  created_at: string;
  updated_at: string;
};

export * from "./fingerprint";
export * from "./identityMatch";
export * from "./lifecycle";
export * from "./auctionEvent";
export * from "./history";
export * from "./provenance";
export * from "./fromProperty";
