export type Property = {
  id: string;
  title: string;
  description: string | null;
  province: string;
  town: string;
  suburb: string | null;
  address: string | null;
  property_type: string;
  bedrooms: number;
  bathrooms: number;
  garages: number;
  estimated_value: number;
  auction_price: number;
  auction_date: string;
  status: string;
  source: string | null;
  created_at: string;
  updated_at: string;
  image?: string | null;
  thumbnail?: string | null;
  heroImage?: string | null;
  hero_image?: string | null;
  medium_image?: string | null;
  thumbnail_image?: string | null;
  blur_placeholder?: string | null;
  latitude?: number | null;
  longitude?: number | null;
};
