export type Property = {
  id: string;
  title: string;
  description: string | null;
  province: string;
  town: string;
  suburb: string | null;
  address: string | null;
  street_address?: string | null;
  postal_code?: string | null;
  country?: string | null;
  municipality?: string | null;
  region?: string | null;
  property_type: string;
  bedrooms: number;
  bathrooms: number;
  garages: number;
  erf_size?: number | null;
  floor_size?: number | null;
  estimated_value: number;
  auction_price: number;
  reserve_price?: number | null;
  auction_date: string;
  auction_time?: string | null;
  auction_venue?: string | null;
  auction_agency?: string | null;
  agency_contact?: string | null;
  agency_website?: string | null;
  status: string;
  listing_status?: string | null;
  source: string | null;
  source_name?: string | null;
  source_url?: string | null;
  external_listing_id?: string | null;
  imported_at?: string | null;
  last_verified_at?: string | null;
  data_classification?: string | null;
  data_quality_score?: number | null;
  address_display_mode?: string | null;
  provenance_notes?: string | null;
  registration_required?: boolean | null;
  deposit_required?: boolean | null;
  terms_link?: string | null;
  brochure_link?: string | null;
  catalogue_link?: string | null;
  created_at: string;
  updated_at: string;
  image?: string | null;
  thumbnail?: string | null;
  heroImage?: string | null;
  hero_image?: string | null;
  medium_image?: string | null;
  thumbnail_image?: string | null;
  blur_placeholder?: string | null;
  latitude?: number | null;
  longitude?: number | null;
};
